version: 0.0
os: linux
files:
  - source: target/awsStart.war
    destination: /var/www/html/webapp
permissions:
  - object: /var/www/html/webapp
    pattern: "*"
    owner: tomcat
    group: tomcat
    mode: 777
    type:
      - file    
hooks:
  BeforeInstall:
    - location: scripts/clean_service.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/change_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
#    - location: scripts/create_test_db.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root